ADASProject/ADASProject/Controllers/EditController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ADASProject.Models;
using ADASProject.Products;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ADASProject.Controllers
{
    public class EditController : Controller
    {
        IDbContext db;

        public EditController(IDbContext context)
        {
            db = context;
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> ChouseAdd()
        {
            var types = ReflectionHelper.GetAllProductClasses();
            var nameToTypeDict = ReflectionHelper.CreateNameToTypeDict(types, typeof(Attributes.ClassName));
            var model = new AddModel() { ProductNames = nameToTypeDict.Keys.ToArray() };
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Add(AddModel model)
        {
            var types = ReflectionHelper.GetAllProductClasses();
            var nameToTypeDict = ReflectionHelper.CreateNameToTypeDict(types, typeof(Attributes.ClassName));

            if (nameToTypeDict.ContainsKey(model.Name))
                model.Name = nameToTypeDict[model.Name];
            else
                return RedirectToAction("Error", new ErrorViewModel() { ActionName = "Index", RequestInfo = "Type is not found" });

            var type = ReflectionHelper.FoundType(model.Name);
            var newModel = ReflectionHelper.CreateAddModelByType(type);

            newModel.Name = model.Name;

            return View(newModel);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> AddHelper(AddModel model)
        {
            var description = ReflectionHelper.CreateProductDescription(model.Name, model.Values);
            var productInfo = ReflectionHelper.CreateProductInfo(model.StandartInfoValues, true);

            if (description == null || productInfo == null)
                return RedirectToAction(
                    "Error",
                    new ErrorViewModel() { ActionName = "Index", RequestInfo = "Product creation error!" });

            var product = Product<IDescription>.GetProduct(description, productInfo);
            product.ProductInfo.Image = ControllerHelper.ConvertFileToBytes(model.Image);
            await db.TryToAddProductAsync(product);
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public async Task<IActionResult> Error(ErrorViewModel model)
        {
            if (model == null)
                model = new ErrorViewModel();
            return View(model);
        }
    }
}

ADASProject/ADASProject/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ADASProject.Models;
using ADASProject.Notifications;
using ADASProject.Order;
using ADASProject.Products;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ADASProject.Controllers
{
    public class OrderController : Controller
    {
        IDbContext db;

        public OrderController(IDbContext context)
        {
            db = context;
        }

        [HttpGet]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public async Task<IActionResult> Error(ErrorViewModel model)
        {
            if (model == null)
                model = new ErrorViewModel();
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Buy(int id)
        {
            var value = new byte[0];
            if (HttpContext.Session.Keys.Contains("basket"))
                value = HttpContext.Session.Get("basket");

            if (!await db.IsAvailable(id))
                return RedirectToAction("Error", 
                    new ErrorViewModel()
                    {
                        ActionName = "Catalog",
                        RequestInfo = "Product not available"
                    });

            HttpContext.Session.Set("basket", value.AddValue(id));

            return RedirectToAction("Basket");
        }

        [HttpGet]
        public async Task<IActionResult> Basket()
        {
            if (!HttpContext.Session.Keys.Contains("basket"))
                return View(new BasketModel() { Products = new Dictionary<ProductInfo, int>() });

            var basket = HttpContext.Session.Get("basket");
            var values = basket.GetValues();

            var model = new BasketModel();

            foreach (var value in values)
            {
                var product = await db.GetProductInfoAsync(value.Key);
                model.Products.Add(product, value.Value);
                model.Amount += product.Price * value.Value;
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> RemoveProduct(int id)
        {
            if (!HttpContext.Session.Keys.Contains("basket"))
                return RedirectToAction("Index", "Home");

            var basket = HttpContext.Session.Get("basket");
            basket.RemoveValue(id);
            HttpContext.Session.Set("basket", basket);

            return RedirectToAction("Basket");
        }

        [HttpPost]
        public async Task<IActionResult> ChangeCount(BasketModel model)
        {
            if (!HttpContext.Session.Keys.Contains("basket"))
                return RedirectToAction("Index", "Home");

            if (model.Count > 65535 || model.Count < 0 || !await db.HasQuantity(model.Id, model.Count))
                return RedirectToAction("Error",
                    new ErrorViewModel()
                    {
                        ActionName = "Basket",
                        RequestInfo = "This count not available!"
                    });

            var basket = HttpContext.Session.Get("basket");
            basket.ChangeCount(model.Id, (byte)model.Count);
            HttpContext.Session.Set("basket", basket);
            return RedirectToAction("Basket");
        }

        [HttpGet]
        [Authorize(Roles = "admin, user")]
        public async Task<IActionResult> Sending()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "admin, user")]
        public async Task<IActionResult> Payment()
        {
            if (!HttpContext.Session.Keys.Contains("basket"))
                return RedirectToAction("Error",
                    new ErrorViewModel()
                    {
                        ActionName = "Basket",
                        RequestInfo = "Your basket is empty!"
                    });

            var basket = HttpContext.Session.Get("basket");
            var values = basket.GetValues();
            double amount = 0.0;
            foreach(var value in values)
            {
                var product = await db.GetProductInfoAsync(value.Key);
                amount += product.Price * value.Value;
            }
            return View(new OrderModel() { Amount =  amount, SecretCode = "R9J3D3WC" });
        }

        [HttpGet]
        [Authorize(Roles = "admin, user")]
        public async Task<IActionResult> Placement()
        {
            var model = new OrderModel();
            model.CityIndex = -1;

            model.Places = new List<string>()
            {
                "Elabuga, Mira 34",
                "Kazan', Kremlevskaya 35A",
                "Kazan', Gvardeyskaya 12",
                "Moscow, Sovetckaya 21B"
            };

            var city = (string)TempData.Peek("city");

            if (city != null && city.Length > 0)
                for (int i = 0; i < model.Places.Count; i++)
                    if (model.Places[i].StartsWith(city))
                        model.CityIndex = i;

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "admin, user")]
        public async Task<IActionResult> Order(OrderModel model)
        {
            if (!HttpContext.Session.Keys.Contains("basket") || TempData.Peek("id") == null)
                return RedirectToAction("Index", "Home");

            var basket = HttpContext.Session.Get("basket");
            var values = basket.GetValues();

            var orderInfo = new OrderInfo();
            foreach (var item in values)
            {
                if (await db.HasQuantity(item.Key, item.Value))
                {
                    var product = await db.GetProductInfoAsync(item.Key);
                    orderInfo.SubOrders.Add(new SubOrder() { ProductId = item.Key, Count = item.Value });
                    orderInfo.Amount += product.Price * item.Value;
                }
                else
                {
                    var productName = await db.GetProductInfoAsync(item.Key);
                    return RedirectToAction("Error",
                        new ErrorViewModel()
                        {
                            ActionName = "Basket",
                            RequestInfo = $"Not available {item.Value} products in stock ({productName})"
                        });
                }
            }

            var userId = (int)TempData.Peek("id");
            orderInfo.UserId = userId;
            orderInfo.StatusInfo = Status.Review;
            orderInfo.OrderTime = DateTime.Now;


            if (!await db.TryToSaveOrderAsync(orderInfo))
                return base.RedirectToAction("Error", 
                     new ErrorViewModel()
                     {
                         ActionName = "Basket",
                         RequestInfo = $"Error creating order. Some products may be missing."
                     });

            HttpContext.Session.Remove("basket");

            await NotificationService.Service.SendOrderNotificationAsync((string)TempData.Peek("username"), orderInfo, Status.Review);

            return View();
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> GetOrders()
        {
            var model = new GetOrdersModel();
            // Get all orders from DB
            var orders = await db.GetOrdersAsync();
            foreach (var order in orders)
            {
                // Add all sub orders from this order
                model.Products.Add(order, new List<Tuple<ProductInfo, int>>());
                var subOrders = await db.GetSubOrdersAsync(order.Id);
                foreach (var subOrder in subOrders)
                {
                    var product = await db.GetProductInfoAsync(subOrder.ProductId);
                    model.Products[order].Add(Tuple.Create(product, subOrder.Count));
                }
            }
            return View(model);
        }

        [HttpGet]
        [Authorize(Roles = "admin, user")]
        public async Task<IActionResult> GetOrder(int id)
        {
            var order = await db.GetOrderAsync(id);

            if (order.UserId != (int)TempData.Peek("id") && "admin" != (string)TempData.Peek("role"))
                return RedirectToAction("Error",
                           new ErrorViewModel()
                           {
                               ActionName = "GetOrders",
                               RequestInfo = $"You dont have permissions."
                           });

            if (order == null)
                return RedirectToAction("Error", "Home",
                           new ErrorViewModel()
                           {
                               ActionName = "Index",
                               RequestInfo = $"Order with id = {id} doesn't exist."
                           });

            // Get sub orders
            order.SubOrders = await db.GetSubOrdersAsync(order.Id);
            // Create list of subOrders
            var list = new List<Tuple<ProductInfo, int>>();
            // Fill sub orders info
            foreach (var subOrder in order.SubOrders)
            {
                var product = await db.GetProductInfoAsync(subOrder.ProductId);
                list.Add(Tuple.Create(product, subOrder.Count));
            }
            // Create and return model
            var model = new GetOrderModel() { Order = order, SubOrders = list, Status = order.StatusInfo, Role = (string)TempData.Peek("role") };
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "admin, user")]
        public async Task<IActionResult> ChangeOrder(GetOrderModel model)
        {
            var order = await db.GetOrderAsync(model.Order.Id);
            // Get user
            var user = await db.GetUserAsync(order.UserId);

ADASProject/ADASProject/Views/Home/Catalog.cshtml
@model CatalogModel

<!DOCTYPE HTML>
<html>
<head>
    <style>
        .float-input {
            float: left
        }
    </style>

    <style>
        .b {
            width: 80px;
            height: 30px;
            border-radius: 3px;
        }

        .a {
            text-decoration: none;
            outline: none;
            display: inline-block;
            width: 140px;
            height: 45px;
            line-height: 45px;
            border-radius: 45px;
            margin: 10px 20px;
            font-family: 'Montserrat', sans-serif;
            font-size: 11px;
            text-transform: uppercase;
            text-align: center;
            letter-spacing: 3px;
            font-weight: 600;
            color: #524f4e;
            background: white;
            box-shadow: 0 8px 15px rgba(0,0,0,.1);
            transition: .3s;
        }

            .a:hover {
                background: #A0A0A0;
                box-shadow: 0 15px 20px #AFAFAF;
                color: white;
                transform: translateY(-7px);
            }
    </style>
</head>
<body>
    <div class="top_bg">

    </div>
    <div class="header_bg">
        <div class="container">
            <div class="header">
                <div class="head-t">
                    <div class="header_right">
                        <div class="clearfix"> </div>
                    </div>
                    <div class="clearfix"> </div>
                </div>
                <ul class="megamenu skyblue">
                    <li class="active grid"><a class="color1" asp-action="Index">Home</a></li>
                    <li class="active grid"><a class="color1" asp-action="Catalog">Catalog</a></li>
            </div>

            <!-- content -->
            <div class="container">
                <div class="women_main">
                    <!-- start sidebar -->
                    <div class="col-md-3 s-d">
                        <div class="w_sidebar">
                            <section class="sky-form">
                                <h4>categories</h4>
                                <form asp-controller="Home" asp-action="Catalog" method="get">
                                    <div class="row1 scroll-pane">
                                        <div class="col col-4">
                                            @foreach (var check in CatalogModel.TypeToNameDict)
                                            {
                                                <label><button class="a" name="CategoryName" value="@check.Key" asp-controller="Home" asp-action="Catalog">@check.Value</button></label>
                                            }
                                        </div>
                                    </div>
                                </form>

                            </section>
                            <form asp-controller="Home" asp-action="Catalog" method="get">
                                <section class="sky-form">
                                    <h4>Filters</h4>
                                    <div class="row1 scroll-pane" style="height:auto">
                                        <div class="col col-4">
                                            @for (int i = 0; i < Model.StandartValuesInfo.Types.Length; i++)
                                            {
                                                @switch (Model.StandartValuesInfo.Types[i].Name)
                                                {
                                                    case "Double":
                                                        {
                                                            <p>@Model.StandartValuesInfo.Descriptions[i]: </p><input class="float-input, b" maxlength="16" type="number" step="0.1" asp-for="StandartValuesInfo.FromValues[i]" /><input class="b" maxlength="16" type="number" step="0.1" asp-for="StandartValuesInfo.ToValues[i]" />;
                                                            break;
                                                        }

                                                    case "Int32":
                                                        {
                                                            <p>@Model.StandartValuesInfo.Descriptions[i]: </p><input class="float-input, b" maxlength="16" type="number" asp-for="StandartValuesInfo.FromValues[i]" /><input class="b" maxlength="16" type="number" asp-for="StandartValuesInfo.ToValues[i]" />;
                                                            break;
                                                        }
                                                    default:
                                                        {
                                                            <p>@Model.StandartValuesInfo.Descriptions[i]: </p><input class="float-input, b" maxlength="100" type="text" asp-for="StandartValuesInfo.FromValues[i]" /><input class="b" maxlength="100" type="text" asp-for="StandartValuesInfo.ToValues[i]" />;
                                                            break;
                                                        }
                                                }
                                            }
                                            <br />
                                            @for (int i = 0; i < Model.CustomValuesInfo.Types.Length; i++)
                                            {
                                                @switch (Model.CustomValuesInfo.Types[i].Name)
                                                {
                                                    case "Double":
                                                        {
                                                            <p>@Model.CustomValuesInfo.Descriptions[i]: </p><input class="float-input, b" maxlength="16" type="number" step="0.1" asp-for="CustomValuesInfo.FromValues[i]" /><input class="b" type="number" maxlength="16" step="0.1" asp-for="CustomValuesInfo.ToValues[i]" />;
                                                            break;
                                                        }

                                                    case "Int32":
                                                        {
                                                            <p>@Model.CustomValuesInfo.Descriptions[i]: </p><input class="float-input, b" maxlength="16" type="number" asp-for="CustomValuesInfo.FromValues[i]" /><input class="b" maxlength="16" type="number" asp-for="CustomValuesInfo.ToValues[i]" />;
                                                            break;
                                                        }
                                                    default:
                                                        {
                                                            <p>@Model.CustomValuesInfo.Descriptions[i]: </p><input class="float-input, b" maxlength="100" type="text" asp-for="CustomValuesInfo.FromValues[i]" /><input class="b" maxlength="100" type="text" asp-for="CustomValuesInfo.ToValues[i]" />;
                                                            break;
                                                        }
                                                }
                                            }
                                            <input type="text" value="@Model.CategoryName" asp-for="CategoryName" hidden />
                                            <br /><button class="a" style="margin-left:10px" asp-controller="Home" asp-action="Catalog">Submit</button>
                                        </div>
                                    </div>
                                </section>
                                <section class="sky-form">
                                    <h4>Sort</h4>
                                    <div class="row1 scroll-pane">
                                        <div class="col col-4">
                                            @if (Model.SortedBy == null)
                                            {
                                                <label><input type="radio" name="SortedBy" checked />Not sorted</label>
                                            }
                                            else
                                            {
                                                <label><input type="radio" name="SortedBy" />Not sorted</label>
                                            }
                                            @if (Model.SortedBy == "Price")
                                            {
                                                <label><input asp-for="SortedBy" type="radio" name="SortedBy" value="Price" checked />Sorted by price</label>
                                            }
                                            else
                                            {
                                                <label><input asp-for="SortedBy" type="radio" name="SortedBy" value="Price" />Sorted by price</label>
                                            }
                                            @if (Model.SortedBy == "Rating")
                                            {
                                                <label><input asp-for="SortedBy" type="radio" name="SortedBy" value="Rating" checked />Sorted by rating</label>
                                            }
                                            else
                                            {
                                                <label><input asp-for="SortedBy" type="radio" name="SortedBy" value="Rating" />Sorted by rating</label>
                                            }

                                            <br />
                                            <label><input asp-for="SortedByDescending" type="checkbox" />Sort by descending</label>
                                            <button class="a" style="margin-left:10px; vertical-align:bottom" asp-controller="Home" asp-action="Catalog">Submit</button>
                                        </div>
                                    </div>
                                </section>
                            </form>
                        </div>
                    </div>
                    <!-- start content -->
                    <div class="col-md-9 w_content">
                        <div class="women">
                            <a href="#"><h4>Result - <span>@Model.Count items</span> </h4></a>
                            <div class="clearfix"></div>
                        </div>
                        <!-- grids_of_4 -->

                        @foreach (var category in Model.Products.GroupBy(pr => pr.TableName).Select(group => group.ToArray()))
                        {
                            for (int i = 0; i < category.Length;)
                            {
                                var size = CatalogModel.TypeToSizeDict[ModelHelper.GetCategoryName(category[i].TableName)];
                                var heightPlus100 = size.Height + 100;
                                <div class="grids_of_4">
                                    @for (int j = i; j < i + 4 && j < category.Length; j++)
                                    {
                                        var base64 = Convert.ToBase64String(category[j].Image);
                                        var imgSrc = String.Format("data:image/gif;base64,{0}", base64);

                                        <div class="grid1_of_4">
                                            <div class="content_box" style="width:100%">
                                                <a asp-controller="Product" asp-action="Get/@category[j].Id">
                                                    <div style="height:@(CatalogModel.TypeToSizeDict[ModelHelper.GetCategoryName(category[i].TableName)].Height)px;margin-top:10px; width:100%">
                                                        <img src="@imgSrc" style="width:auto; max-width:100%; height:100%" alt="" />
                                                    </div>
                                                </a>
                                                <div style="height:40px">
                                                    <h4>@category[j].Name</h4>
                                                </div>
                                                <h5>@CatalogModel.TypeToNameDict[ModelHelper.GetCategoryName(category[i].TableName)]</h5>
                                                <div class="grid_1 simpleCart_shelfItem">
                                                    <div class="item_add"><h5 class="item_price">Price: @category[j].Price$</h5></div>
                                                    <div class="item_add"><span class="item_price"><a style="background-color:teal" asp-controller="Order" asp-action="Buy/@category[j].Id">add to cart</a></span></div>
                                                </div>
                                            </div>
                                        </div>
                                    }
                                    @{i += 4;}
                                </div>
                            }
                            <div class="clearfix"></div>
                            <br />
                        }
                    </div>
                    <div class="clearfix"></div>

                    <!-- end content -->
                </div>
            </div>
        </div>
    </div>
</body>
</html>

ADASProject/ADASProject/Views/Home/EditerT.cshtml
@model EditerTModel
    <form asp-controller="Home" asp-action="EditT" method="post">
        <pre>Time = @Model.TimeInTicks (ticks)</pre>
        @for (int i = 0; i < Model.Types.Length; i++)
        {
            @switch (Model.Types[i].Item2.PropertyType.Name)
            {
                default:
                    {
                        <p>@Model.Types[i].Item1: </p>
                        <input type="text" value="@Model.StandartValues[i]" asp-for="Values[i]" required />
                        ;
                        break;
                    }

                case "Double":
                    {
                        <p>@Model.Types[i].Item1: </p>
                        <input type="number" step="0.1" value="@Model.StandartValues[i]" asp-for="Values[i]" required />
                        ;
                        break;
                    }

                case "Int32":
                    {
                        <p>@Model.Types[i].Item1: </p>
                        <input type="number" value="@Model.StandartValues[i]" asp-for="Values[i]" required />
                        ;
                        break;
                    }
            }
            @if (Model.Types[i].Item3)
            {
                <p>*</p>
            }
        }
        <button>Submit</button>
    </form>

ADASProject/ADASProject/Views/Home/PersonalArea.cshtml
@model PersonalAreaModel
<h2>Welcome, @TempData.Peek("username")!</h2>
@if (Model.Orders.Length > 0)
{
<h4>Your orders (@Model.Orders.Length):</h4>
    foreach(var order in Model.Orders)
    {
        <pre>(@order.OrderTime) Amount = @order.Amount, Status = @order.StatusInfo      <a asp-controller="Order" asp-action="GetOrder/@order.Id">Details</a></pre>
    }
}

@if (TempData.Peek("role") != null && TempData.Peek("role").ToString() == "admin")
{
    <a asp-controller="Edit" asp-action="ChouseAdd"><pre>Add product</pre></a>
    <a asp-controller="Edit" asp-action="ChouseRemove"><pre>Remove product</pre></a>
    <a asp-controller="Order" asp-action="GetOrders"><pre>Check order list</pre></a>
}

ADASProject/ADASProject/Views/Home/SetCity.cshtml
@model SetCityModel
<head>
    <style>
        .select_or{
            border-radius: 4px 5px;
            border-width: 3px;
            border: solid;
            background-color:#f0f0f0;
            margin-left:10px;
            margin-bottom:10px;
        }
        .button_new{
            border-radius: 4px 5px;
            border-width: 3px;
            border: solid;
            background-color:#f0f0f0;
            margin-left:5px;
            margin-bottom:10px;
        }
    </style>
</head>
<body>
    <h4>Chouse your city</h4>
    <form asp-controller="Home" asp-action="SetCity" method="post">
        <select class="select_or" asp-for="City">
            @foreach (var city in Model.Cities)
            {
                <option value="@city">@city</option>
            }
        </select>
        <button class="button_new">Submit</button>
        <br />
        <a asp-controller="Home" asp-action="SetCustomCity">I didn't find my sity...</a>
    </form>
</body>

ADASProject/ADASProject/Views/Home/SetCustomCity.cshtml
@model SetCityModel
<head>
    <style>
        .button_new {
            border-radius: 4px 5px;
            border-width: 3px;
            border: solid;
            background-color: #f0f0f0;
            margin-left: 5px;
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
    <h4>Write your city</h4>
    <form asp-controller="Home" asp-action="SetCity" method="post">
        <input asp-for="City" type="text" required/>
        <button class="button_new">Submit</button>
    </form>
</body>